# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AParent-Life
email: ventopowah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
  AParentLife is an outreach for new and veteran parents to make a 
  healthy lifestyle switch and show our kids how to be 
  <h1>Healthy, Happy and Strong!</h1>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AParent-life.com" # the base hostname & protocol for your site
twitter: @VentoPowah
SnapChat:  AParentLife
FaceBook: @AParentLife

# Build settings
markdown: kramdown
